# Generated by Django 3.2.2 on 2022-02-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='mail',
            new_name='email',
        ),
    ]
