# Generated by Django 3.2.2 on 2022-02-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_rename_mail_contacts_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('email', models.EmailField(max_length=200, verbose_name='Почта')),
                ('notes', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Запрос обратной связи',
                'verbose_name_plural': 'Запросы обратной связи',
            },
        ),
    ]
