# Generated by Django 3.2.2 on 2022-02-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_contactsme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryForQDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Цена от дней хранения',
                'verbose_name_plural': 'Цены от дней хранения',
            },
        ),
        migrations.CreateModel(
            name='PriceForVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(verbose_name='Объём (см^3)')),
                ('price', models.IntegerField(verbose_name='Цена за см^3, при данном весе')),
                ('type', models.CharField(choices=[('MIN', 'Минимальный'), ('DEF', 'Обычный'), ('MAX', 'Максимальный')], default='DEF', max_length=40, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Цена от объёма',
                'verbose_name_plural': 'Цены от объёма',
            },
        ),
        migrations.CreateModel(
            name='PriceForWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_country', models.CharField(max_length=200, verbose_name='Страна отправления')),
            ],
            options={
                'verbose_name': 'Цена от страны',
                'verbose_name_plural': 'Цены от стран',
            },
        ),
        migrations.CreateModel(
            name='PriceForWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='Вес (кг)')),
                ('price', models.IntegerField(verbose_name='Цена за кг, при данном весе')),
                ('type', models.CharField(choices=[('MIN', 'Минимальный'), ('DEF', 'Обычный'), ('MAX', 'Максимальный')], default='DEF', max_length=40, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Цена от веса',
                'verbose_name_plural': 'Цены от веса',
            },
        ),
        migrations.CreateModel(
            name='PriceForWayTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_country', models.CharField(max_length=200, verbose_name='Страна получения')),
                ('price_for_way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forWayTo', to='transportation.priceforway')),
            ],
            options={
                'verbose_name': 'Страна получения',
                'verbose_name_plural': 'Страны получения',
            },
        ),
        migrations.CreateModel(
            name='PriceForQDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_date', models.IntegerField(verbose_name='Кол-во дней хранения')),
                ('price', models.IntegerField(verbose_name='Цена за день, при данном кол-ве дней')),
                ('country_for_q_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pForQDate', to='transportation.countryforqdate')),
            ],
            options={
                'verbose_name': 'Цена от дней ожидания',
                'verbose_name_plural': 'Цены от дней ожидания',
            },
        ),
        migrations.AddField(
            model_name='countryforqdate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cForQDate', to='transportation.priceforway'),
        ),
    ]
