# Generated by Django 3.2.2 on 2022-02-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_priceforwayto_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceforqdate',
            options={'verbose_name': 'Цена от дней хранения', 'verbose_name_plural': 'Цены от дней хранения'},
        ),
    ]
