# Generated by Django 3.2.2 on 2022-02-25 14:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0007_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status_details',
            field=tinymce.models.HTMLField(blank=True, max_length=3000, null=True, verbose_name='Подрбный статус доставки'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid',
            field=models.BooleanField(default=True, verbose_name='Оплачен?'),
        ),
    ]
