# Generated by Django 3.2.2 on 2022-02-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0010_transactionstatus_date_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstatus',
            name='status_details',
            field=models.CharField(choices=[('1', 'В обработке'), ('2', 'Комплектуется'), ('3', 'На складе'), ('4', 'В пути'), ('5', 'На разгрузке'), ('6', 'Ожидает')], max_length=40, verbose_name='Статус доставки'),
        ),
    ]
